### ISSUE TITLE
Duplicated keys in meta.yaml

### ISSUE THREAD

**Issue by Hogfeldt** [Hogfeldt/bioconda_recipe_gen_ci#1]
The bioconda-util.Recipe class cannot handle duplicate keys. 
An example of a duplicated key is in the package Mira, where there is an url for linux and an url for mac:
```
package:
  name: mira
  version: '4.0.2'

build:
  number: 3
  # TODO - this ought to work on osx as well
  skip: True # [not linux]

source:
  url: https://downloads.sourceforge.net/project/mira-assembler/MIRA/stable/mira_4.0.2_linux-gnu_x86_64_static.tar.bz2 # [linux]
  sha256: d3c74a6b402192e01d10adb8dbdc3450d4033fa0e7662ce5ce5de4f8c1967813 # [linux]
  url: https://downloads.sourceforge.net/project/mira-assembler/MIRA/stable/mira_4.0.2_darwin13.1.0_x86_64_static.tar.bz2 # [osx]
  sha256: 3cdfba4be7bde1a97b15259b9fd3216c4369d906ea20f5f360f30dc0d83e7b8e # [osx]

# No build requirements as using the author's binaries.
requirements:
  build:
  run:

test:
  commands:
    - mira --help

about:
  home: https://sourceforge.net/p/mira-assembler/wiki/Home/
  license: 'GNU General Public License v2 or later (GPLv2+)'
  license_file: LICENCE
  summary: 'MIRA is a whole genome shotgun and EST sequence assembler for Sanger, 454, Solexa (Illumina), IonTorrent data and PacBio (the later at the moment only CCS and error-corrected CLR reads)'

extra:
  identifiers:
    - biotools:mira
```
